language: java
dist: xenial
sudo: required
jdk: openjdk8

env:
  - RELEASE_VERSION="1.0.0"

git:
  quiet: true
notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/minecraft/deobfedDeps/providedDummy.jar
  - rm -f  $HOME/.gradle/caches/minecraft/deobfedDeps/compileDummy.jar
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradlew
  - if [[ $TRAVIS_BRANCH == "SNAPSHOT" ]]; then
      export IS_SNAPSHOT=true;
    fi

install:
  - ./gradlew setupCIWorkspace build -s --refresh-dependencies

before_deploy:
  - git config --local user.name "Travis"
  - git config --local user.email "github@unaussprechlich.net"
  - if [ $TRAVIS_BRANCH == "SNAPSHOT"]; then
      git tag -a SNAPSHOT_$TRAVIS_BUILD_NUMBER -m "Automated snapshot build. Download and run the .jar to install and use the latest snapshot build!"
    fi
  - if [ $TRAVIS_BRANCH == "master"]; then
    git tag -a $RELEASE_VERSION -m "Automated release build. Download and run the .jar to install and use the latest release build!"
    fi

deploy:
  - provider: releases
    token: $GIT_TOKEN
    skip_cleanup: true
    file_glob: true
    file: $TRAVIS_BUILD_DIR/build/libs/*
    prerelease: true
    on:
      branch: SNAPSHOT
  - provider: releases
    token: $GIT_TOKEN
    skip_cleanup: true
    file_glob: true
    file: $TRAVIS_BUILD_DIR/build/libs/*
    on:
      branch: master
