language: java
jdk:
  - openjdk8
os:
  - linux
sudo: required

git:
  quiet: true
notifications:
  email: false

before_install:
  - chmod +x gradlew
  - ./gradlew wrapper --gradle-version 4.10.3
  - echo $TRAVIS_BUILD_NUMBER > $TRAVIS_BUILD_DIR/src/main/resources/build_number.txt

deploy:
  - provider: releases
    token: $GIT_TOKEN
    skip_cleanup: true
    file_glob: true
    release_number: SNAPSHOT_$TRAVIS_COMMIT
    file: $TRAVIS_BUILD_DIR/build/libs/*
    prerelease: true
    on:
      branch: SNAPSHOT
  - provider: releases
    token: $GIT_TOKEN
    skip_cleanup: true
    file_glob: true
    release_number: RELEASE_TODO
    file: $TRAVIS_BUILD_DIR/build/libs/*
    on:
      branch: master
