language: java
jdk:
  - openjdk8
os:
  - linux
sudo: required

git:
  quiet: true
notifications:
  email: false

branches:
  only:
    - SNAPSHOT

before_install:
  - chmod +x gradlew
  - ./gradlew wrapper --gradle-version 4.10.3
  - echo $TRAVIS_BUILD_NUMBER > $TRAVIS_BUILD_DIR/src/main/resources/build_number.txt

before_deploy:
  - git config --local user.name "Travis"
  - git config --local user.email "github@unaussprechlich.net"
  - git tag -a $TRAVIS_BUILD_NUMBER -m "Automated snapshot build. Download and run the above .jar to install and use this snapshot build!"

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  skip_cleanup: true
  file_glob: true
  file: $TRAVIS_BUILD_DIR/build/libs/*
  on:
    repo: unaussprechlich/warlordsplus
    prerelease: true
if: tag IS blank